import { Canvas } from "@react-three/fiber";
import Head from "next/head";
import { useState } from "react";
import { RoundedBox, Text, useCursor } from "@react-three/drei";

export default function Home() {
  function Cube({
    position,
    color,
    size,
  }: {
    position: [number, number, number];
    color: string;
    size: [number, number, number];
  }) {
    return (
      <mesh position={position}>
        <RoundedBox
          args={size} // Width, Height, Depth
          radius={0.1} // Corner radius
          smoothness={4} // Smoother corners
        >
          <meshStandardMaterial color={"white"} />
        </RoundedBox>
        <meshStandardMaterial color={color} />
        <group position={[0, -0.03, 0]}>
          <QuestionPane
            size={[2.8, 1.5, 1]}
            position={[0, 0.2, 0.1]}
            questionText="What is the Question?"
          />
          <BottomRow size={[2.8, 0.3, 1]} position={[0, -0.745, 0.1]} />
        </group>
      </mesh>
    );
  }

  const QuestionPane = ({
    size,
    position,
    questionText,
  }: {
    size: [number, number, number];
    position: [number, number, number];
    questionText: string;
  }) => {
    return (
      <mesh position={position}>
        <RoundedBox
          args={size} // Width, Height, Depth
          radius={0.1} // Corner radius
          smoothness={4} // Smoother corners
        >
          <meshStandardMaterial color={"lightgreen"} />
        </RoundedBox>
        <Text
          position={[0, 0, 1]}
          fontSize={0.1}
          color="black"
          anchorX="center"
          anchorY="middle"
        >
          {questionText}
        </Text>
      </mesh>
    );
  };

  const BottomRow = ({
    size,
    position,
  }: {
    size: [number, number, number];
    position: [number, number, number];
  }) => {
    return (
      <mesh position={position}>
        <RoundedBox
          args={size} // Width, Height, Depth
          radius={0.1} // Corner radius
          smoothness={4} // Smoother corners
        >
          <meshStandardMaterial color={"lightgreen"} />
          <group>
            <ClickableButton
              size={[0.6, 0.2]}
              position={[0.8, 0.13, 1.2]}
              buttonText="Next &#10095;"
              color="lightGreen"
            />
            <ClickableButton
              size={[0.6, 0.2]}
              position={[0, 0.13, 1.2]}
              buttonText="Show Solution"
              color="lightGreen"
            />
            <ClickableButton
              size={[0.6, 0.2]}
              position={[-0.8, 0.13, 1.2]}
              buttonText="&#10094; Previous"
              color="lightGreen"
            />
          </group>
        </RoundedBox>
      </mesh>
    );
  };
  const ClickableButton = ({
    size,
    position,
    buttonText,
    color,
  }: {
    size: [number, number];
    position: [number, number, number];
    buttonText: string;
    color?: string;
  }) => {
    const [hovered, setHovered] = useState(false);
    useCursor(hovered);
    return (
      <group position={position}>
        <mesh
          onPointerOver={() => setHovered(true)}
          onPointerOut={() => setHovered(false)}
          onClick={() => console.log({ buttonText })}
        >
          <planeGeometry args={size} />
          <meshStandardMaterial color={color} />
        </mesh>
        <Text
          position={[0, 0, 0]}
          fontSize={0.1}
          color="black"
          anchorX="center"
          anchorY="middle"
        >
          {buttonText}
        </Text>
      </group>
    );
  };
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="h-screen w-full">
          <Canvas>
            <ambientLight intensity={2} />
            <Cube position={[0, 0, 0]} color="red" size={[3, 2, 1]} />
          </Canvas>
        </div>
      </main>
    </>
  );
}
